DefaultContentLanguage = "en"

baseURL = "/"
title = "Markus Poerschke"
author = "Markus Poerschke"
name = "Markus Poerschke"
theme = "markuspoerschke"

pygmentsCodefences = true
pygmentsStyle = "github"
pygmentsUseClasses = true

[params]
robots = "index, follow"
description = "I am a software engineer from Velbert (Germany). In my blog I share my work expirience."

[params.navigation]
about_me  = "About me"

[languages]
[languages.en]
languageCode = "en-us"
weight = 1
languageName = "Read this article in English"

[languages.de]
languageCode = "de-de"
weight = 2
languageName = "Diesen Beitrag auf Deutsch lesen"
[languages.de.params]
description = "Ich bin Software-Engineer aus Velbert. In meinem Blog schreibe ich über meine Erfahrung in der Softwareentwicklung."
[languages.de.params.navigation]
about_me  = "Über mich"

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true  # Enable user to embed HTML snippets in Markdown content.