DefaultContentLanguage = "en"

baseURL = "/"
title = "Markus Poerschke"
author = "Markus Poerschke"
name = "Markus Poerschke"
theme = "markuspoerschke"

pygmentsCodefences = true
pygmentsStyle = "github"
pygmentsUseClasses = true

[params]
robots = "index, follow"

[params.navigation]
about_me  = "About me"

[languages]
[languages.en]
languageCode = "en-us"
weight = 1
languageName = "Read this article in English"

[languages.de]
languageCode = "de-de"
weight = 2
languageName = "Diesen Beitrag auf Deutsch lesen"
[languages.de.params]
[languages.de.params.navigation]
about_me  = "Über mich"
