name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dokku Deployment
        uses: vitalyliber/dokku-github-action@master
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          HOST: markus.poerschke.nrw
          PROJECT: markus-poerschke-nrw
          BRANCH: master
